// packages/react/src/components/spinner/Spinner.tsx
import type { SpinnerProps } from "@apiary-ui/core";
import { spinnerVariants } from "@apiary-ui/core";
import { cn } from "tailwind-variants";
import { Loader2Icon } from "lucide-react";
import type { ComponentProps } from "react";

interface Props extends ComponentProps<"svg">, SpinnerProps {}

export function Spinner({ size, className, ...props }: Props) {
  return (
    <Loader2Icon
      data-slot="spinner"
      role="status"
      aria-label="Loading"
      className={cn(spinnerVariants({ size }), className)}
      {...props}
    />
  );
}

// packages/vue/src/components/spinner/Spinner.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { LoaderCircle } from "@lucide/vue";
import type { SpinnerProps } from "@apiary-ui/core";
import { spinnerVariants } from "@apiary-ui/core";
import { cn } from "tailwind-variants";

interface Props extends SpinnerProps {
  class?: HTMLAttributes["class"];
}

const props = withDefaults(defineProps<Props>(), {
  size: "medium",
});
</script>

<template>
  <LoaderCircle
    data-slot="spinner"
    role="status"
    aria-label="loading"
    :class="cn(spinnerVariants({ size: props.size }), props.class)"
  />
</template>
